// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIw4L7ypGPnb9tKrRcTjJN8NR2PCms6_Y',
    appId: '1:336060801673:web:614e9c73f077c30f569c58',
    messagingSenderId: '336060801673',
    projectId: 'music-player-ahmed-2024',
    authDomain: 'music-player-ahmed-2024.firebaseapp.com',
    storageBucket: 'music-player-ahmed-2024.firebasestorage.app',
    measurementId: 'G-R2SY3SMJHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8PWM_SPap_XBC8K489w472hgj9tktq2o',
    appId: '1:336060801673:android:366c43dd38941443569c58',
    messagingSenderId: '336060801673',
    projectId: 'music-player-ahmed-2024',
    storageBucket: 'music-player-ahmed-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3tUfWmpt-yO6uhftyEwjDt0smoRyTrkw',
    appId: '1:336060801673:ios:08b3c293d324eccf569c58',
    messagingSenderId: '336060801673',
    projectId: 'music-player-ahmed-2024',
    storageBucket: 'music-player-ahmed-2024.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3tUfWmpt-yO6uhftyEwjDt0smoRyTrkw',
    appId: '1:336060801673:ios:08b3c293d324eccf569c58',
    messagingSenderId: '336060801673',
    projectId: 'music-player-ahmed-2024',
    storageBucket: 'music-player-ahmed-2024.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIw4L7ypGPnb9tKrRcTjJN8NR2PCms6_Y',
    appId: '1:336060801673:web:80e7047242b3e70e569c58',
    messagingSenderId: '336060801673',
    projectId: 'music-player-ahmed-2024',
    authDomain: 'music-player-ahmed-2024.firebaseapp.com',
    storageBucket: 'music-player-ahmed-2024.firebasestorage.app',
    measurementId: 'G-994SGXVDFS',
  );
}
